# Generated by Django 3.2.5 on 2023-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_film_checkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='dropdownlist',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='checkstatus',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
