# Generated by Django 3.2.5 on 2023-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_query', models.TextField()),
                ('output_query', models.TextField()),
            ],
        ),
    ]
