# Generated by Django 3.2.5 on 2023-04-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('year', models.TextField(blank=True)),
                ('filmurl', models.TextField(blank=True)),
                ('genre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.FileField(upload_to='media')),
            ],
        ),
    ]
