# Generated by Django 3.2.5 on 2023-04-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230317_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
