# Generated by Django 3.2.5 on 2023-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230411_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='dropdownlist',
            field=models.TextField(default='New'),
        ),
    ]
