# Generated by Django 3.2.5 on 2023-04-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='checkstatus',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='film',
            name='dropdownlist',
            field=models.TextField(blank=True),
        ),
    ]
