# Generated by Django 3.2.5 on 2023-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230412_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='dropdownlist',
            field=models.TextField(default='New'),
        ),
    ]
